language: node_js

node_js: stable

# 缓存依赖
cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai' # 更改时区

# 依赖安装
install:
  - npm install hexo-cli -g
  - npm install

# 构建脚本
script:
  - hexo douban -bm
  - hexo g
  - cp CNAME public/

# 分支白名单
branches:
  only:
    - hexo # 只对 master 分支进行构建

# GitHub Pages 部署
deploy:
  provider: pages
  skip_cleanup: true
  # 在项目仪表盘的 Settings -> Environment Variables 中配置
  github_token: $GITHUB_TOKEN
  # 将 public 目录下的内容推送到默认的 master 分支上，并不会连带 public 目录一起
  target_branch: master
  local_dir: public
  on:
    branch: hexo

# 通知
notifications:
  email:
    recipients:
      - wangbinxin001@126.com
    on_failure: always
